### ISSUE TITLE
Question about extrinsics

### ISSUE THREAD

**Issue by fangzhou2000** [cvlab-kaist/PF3plat#6]
Hi, I have two questions about extrinsics:

1. Does PF3plat completely avoid using camera extrinsics, both during training and testing?

2. Would incorporating camera extrinsics during training improve the test-time performance? Have you conducted similar experiments? 

I am curious about the above questions because I noticed a similar work [NoPoSplat](https://github.com/cvg/NoPoSplat). It utilizes extrinsics during training while also remaining pose-free at test time, achieving slightly higher metrics than PF3plat. I wonder whether the difference is due to the use of camera extrinsics during training.

**Comment by SunghwanHong** [comment]
1. Yes, for both training and inference, we completely avoid using camera extrinsics. This prevents us from training the network with novel views w/ GT pose like NoPoSplat, which I believe can affect the performance. 
2. As I have not yet tried conducting experiments w/ GT pose, since there may be several ways to incorporate GT pose into our framework, I can not really tell whether I can guarantee to improve the performance. I haven't yet thought of a new way of training our network w/ GT pose yet, so I apologize for the incomplete answer.

**Comment by fangzhou2000** [comment]
Thank you for your reply :)
